---
kind: pipeline
type: exec
name: default
platform:
  os: linux
  arch: amd64
clone:
  disable: true
steps:
- name: clone
  commands:
  - pwd
  - git clone ssh://git@iohub.dev:2222/lxsang/antd-tunnel-publishers.git
  - cd ./antd-tunnel-publishers && git checkout master
- name: build
  commands:
  - cd ./antd-tunnel-publishers
  - libtoolize
  - aclocal
  - autoconf
  - automake --add-missing
  - ./configure --prefix=/opt/cloud/artifacts/runners
  - make
  - make install
trigger:
  branch:
  - master
